### ISSUE TITLE
Реализация ns.View событий для ns.ViewReact

### ISSUE THREAD

**Issue by Rebulus** [yandex-ui/noscript-react#1]
На данный момент ns.View события у ns.ViewReact не обрабатываются при создании вью. Тут нужно решить, хочется ли их поддерживать?

**Замечание:** в React есть методы, которые могут помочь заменить события создания (удаления) элемента. Возможно есть что-то про показ (скрытие).

События потенциально нужны:
1. В реализации корректной работы таймингов: https://github.com/yandex-ui/noscript/blob/master/src/ns.update.js#L352-L362
2. Подписка на глобальные события `ns.events`
3. Cобытие `ns-view-init` для доопределения инстанса `view`

**Comment by Rebulus** [comment]
@vitkarpov было бы круто, если у тебя и команды появилась возможность подумать об этой задаче.

**Comment by vitkarpov** [comment]
Решили, что нужно поддержать встроенные события видов, `ns-view-*`, а DOM-события — в топку. Почему именно так.

Постепенно реактивная вьюшка приобретает смысл поставщика данных, контейнера в редаксовых терминах.

``` js
ns.ViewReact.define('myView', {
  component: {
    render() {
      return <Navigation ...>
        this.getModelData('m', '.items').map((item) => {
           <NavigationItem key={item.key} title={item.title} ... />
        })
        this.createChildren('foo', { ... })
      </Navigation>;
    }
  }
})
```

Эта вьюшка должна уметь достать данные и вызвать необходимые реакт-компоненты прокинув в пропсы нужные данные, соответственно, нет необходимости в DOM-события — все, что касается взаимодействия с пользователем будет обрабатываться в соответствующих компонентах, колбеки из вьюшки придут в пропсах.

Однако, встроенные события вида могу пригодиться:
- для метрики (дернуть на ns-view-show)
- для таймингов (будем считать скорость отрисовки и все такое)

Соответственно, `ns-view-show` должен быть провязан с `componentDidMount`, чтобы получить колбек в тот момент, когда реактовая нода на самом деле находится в DOM и видна.
- для подписок на глобальные события

**Comment by Rebulus** [comment]
У нас есть вот такой `rc` с несовместимостями. Что с ним бум делать?

**Comment by Rebulus** [comment]
https://github.com/yandex-ui/noscript-react/tree/rc-1.1

**Comment by vitkarpov** [comment]
Кажется, нужно будет подмердживать ее в `rc-2.0` :) Вряд ли имеет смысл переходить дважды.

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript-react/pull/34

**Comment by vitkarpov** [comment]
Done https://github.com/yandex-ui/noscript-react/pull/34
