### ISSUE TITLE
Научить расширение подключаться с возможностью передачи ns

### ISSUE THREAD

**Issue by Rebulus** [yandex-ui/noscript-react#11]
При использовании `noscript` на сервере, он подключается как функция, вызов которой инициализирует новый экземпляр `noscript`.

Например

``` js
var NS = require('noscript');
var ns = NS();
```

Необходимо научить расширение принимать экземпляр `noscript`, который оно будет дополнять новыми возможностями.

**Comment by Rebulus** [comment]
@vitkarpov как думаешь, чем лучше собрать итоговый модуль: gulp, grunt, webpack

**Comment by vitkarpov** [comment]
@Rebulus Можно по-хипстерки, а можно галпом :)

**Comment by vitkarpov** [comment]
@Rebulus а это нам нужно или, в итоге, решили отказаться?

**Comment by Rebulus** [comment]
В той реализации сервера, которую вы используете, нет, не надо. Но вообще, по хорошему, для серверного использования надо, т.к. инстанс ns там не известен.

**Comment by Rebulus** [comment]
Если мы сейчас внесём эти изменения, вам придётся при переходе на эту версию изменять текущую логику работы `noscript-react`

**Comment by Rebulus** [comment]
@vitkarpov так что будем с этим делать?

**Comment by vitkarpov** [comment]
@Rebulus кажется, добро. сделаешь пул?

**Comment by Rebulus** [comment]
да, вечером посмотрю и сделаю)

**Comment by Rebulus** [comment]
но это несовместимые изменения с предыдущей версией использования

**Comment by Rebulus** [comment]
https://github.com/yandex-ui/noscript-react/pull/20

**Comment by Rebulus** [comment]
#22
