### ISSUE TITLE
После перерисовки view компонент полностью переинициализируется и теряется свой state

### ISSUE THREAD

**Issue by iEgit** [yandex-ui/noscript-react#13]
Пример

``` jsx

ns.ViewReact.define('view', {
    models: ['foo']
    component: {
        getInitialState() {
            return {
                hello: 'you'
            }
        },

        render() {

            return (
                <div onClick={this.onClick}> 
                   hello
                   {this.state.hello}
                </div>
            );
        },

        onClick() {
            this.setState({hello: 'me'});
            this.props.models.foo.set('.yo', 'yo'); // causes rerendering of parent view
            // and reinitialization of component
            // next text inside div will be 'hello you'

        }
    }

});

```

**Comment by Rebulus** [comment]
Постараюсь сегодня посмотреть, но будет это поздно

**Comment by vitkarpov** [comment]
Мы не спешим :)

**Comment by Rebulus** [comment]
К сожалению, воспроизвести не удалось. Стейт при обновлении вполне сохраняется. Потеря происходит, только если поменялось вью внутри бокса (т.е. поменялись её параметры, а не произошло изменение модели). Но это нормально поведение, т.к. по сути было сформировано новое view. Может быть получится создать тестовую среду с проблемой?

**Comment by vitkarpov** [comment]
@iEgit @Rebulus написал тест на это дело https://github.com/yandex-ui/noscript-react/pull/14

**Comment by Rebulus** [comment]
@vitkarpov судя по всему всё ок, тревис не свалился

**Comment by Rebulus** [comment]
@vitkarpov @iEgit для боксов надо решать. Кажется, что да, стейт надо запоминать, когда возвращаемся обратно к уже созданной вьюшке. А вы что думаете?

**Comment by Rebulus** [comment]
@iEgit @vitkarpov написал тест на это дело для `ns.BoxReact` #15, чтобы было понятно, как это работает сейчас.

**Comment by vitkarpov** [comment]
@Rebulus судя по тесту: правильно ли я понял, что после скрытия вьюшки в боксе и повторном показе стейт сбрасывается (хотя, по идее, экземпляр вьюшки тот же самый)?

**Comment by vitkarpov** [comment]
> судя по всему всё ок, тревис не свалился

для обычной вьюшки все четенько, для бокса пока есть вопрос.

**Comment by Rebulus** [comment]
@vitkarpov да, ты всё правильно понял. По сути, отображение полностью удаляется.

**Comment by Rebulus** [comment]
Можно попробовать сохранять стейт, но я пока не знаю, как это сделать 😄

**Comment by vitkarpov** [comment]
> Можно попробовать сохранять стейт, но я пока не знаю, как это сделать

как минимум, мы должны сформулировать правильное issue. и там уже будем думать:
- точно ли это надо (кейсы, потому что указанный кейс не соответствует)
- если да, то как это сделать

**Comment by vitkarpov** [comment]
Я предлагаю еще зафиксировать текущее поведение стейта (на что сейчас есть рабочие тесты, в итоге) в README.

Сделаю пул тогда.

**Comment by Rebulus** [comment]
Спасибо) Это хорошая идея. Предлагайте кейсы. 

Пока я не вижу смысла сохранять стейт, т.к. реакт будет работать аналогичным способом, что и бокс. 

Например, мы захотим удалить какой-то компонент (а бокс это по сути и делает) и он удалится вместе со стейтом. Когда же вернём его обратно по условию, он будет "девственно" чистым. 

Если нужна фильтация - то это не бокс, а коллекция с определённым выводом.

**Comment by vitkarpov** [comment]
> Если нужна фильтация - то это не бокс, а коллекция с определённым выводом.

Кажется, логичным

**Comment by vitkarpov** [comment]
Обновил README https://github.com/yandex-ui/noscript-react/pull/16

**Comment by vitkarpov** [comment]
> Например, мы захотим удалить какой-то компонент (а бокс это по сути и делает) и он удалится вместе со стейтом. Когда же вернём его обратно по условию, он будет "девственно" чистым.

Конкретный пример.

Есть попап в сайдбаре. Открыли попап, записали в стейт `isOpen`. Перешли на другой урл — показали другой сайдбар (экземпляр). Вернулись в истории браузера к предыдущему урлу, открылся старый сайдбар.

Вопрос: должен ли остаться попап открытым или закрытым?

Кажется, что все-таки новый показ вьюшки это именно сброс стейта, потому что стейт нужен для **сохранения состояния между перерисовками**, а не между показами/скрытиями. Для этого стоит использовать локальные модели.

**Comment by vitkarpov** [comment]
@Rebulus @iEgit что думаете насчет этого кейса?

**Comment by Rebulus** [comment]
Кажется, что всё верно 😄

**Comment by iEgit** [comment]
Мне не нравятся локальные модели - это громоздкий ns подход. Я за то, чтобы можно было использовать state в react компонентах. Вчера договорились, что используем `ns.ViewReact` как `Provider`, который просто поставляет данные. В таком подходе в принципе не так важно, сохраняется state или нет. Можно на это забить. Важно сохранить перерисовки при открытии и закрытии view: я могу хотеть что-нибудь сделать на этих событиях. Например, изменить состояние открытия или закрытия попапа.

**Comment by Rebulus** [comment]
Я не очень понимаю, про открытие и закрытие view. Можешь пояснить?

**Comment by iEgit** [comment]
Я имею в виду, что на открытие и закрытие view должны быть обновления компонента, а также чтобы можно было понять внутри компонента, открыт или закрыт вид.

**Comment by vitkarpov** [comment]
Честно говоря, я пока не понял.

Давай разделим две ситуации:

1.
- вьюшка показалась, сработал getInitialState у компонента
- случился апдейт (например, поменялась модель или по другой причине)
- стейт остается на месте (на это есть тест, это работает)

2.
- экзмпляр вьюшки (например, сайдбар файла) показался в боксе, сработал getInitialState компонента
- дернули апдейт с другими параметрами (выделили в листинге другой файл)
- **новый** экземпляр вьюшки показался в боксе, с ним связан **новый** экземпляр реакт-компонента (они ж должны рисовать разное и быть независимыми), сработал getInitialState для него
- дернули апдейт с предыдущими параметрами (выделили в листинге первый файлик, который уже выделялся)
- показался старый, уже существующий, экземпляр вьюшки и для него опять сработал getInitialState

Вывод — локальный стейт подходит для **сохранения состояния между перерисовками одного и того же экземпляра вьюшки** (сейчас в ns для этой задачи используются локальные модели и это не правильно), а локальные модели нужны для **сохранения состояний между разными экземплярами одной и той же вьюшки в боксе**

**Comment by vitkarpov** [comment]
Вопрос был в том, стоит ли хранить стейт для компонента даже после того как он скрылся в боксе. Пока это кажется лишним (пример с попапом).

**Comment by vitkarpov** [comment]
> чтобы можно было понять внутри компонента, открыт или закрыт вид

можно попробовать `this.props.view.isVisible()`

**Comment by iEgit** [comment]
в принципе да, можно не сохранять, хотя я могу привести пример, когда сохранять хотелось бы: состояния кнопки скачивания файла. После первой загрузки её нужно навсегда дизейблить. Но, как уже говорил, согласно нашей договоренности, мы **не будем** использовать state у ViewReact компонента. Поэтому я считаю, что на это можно забить, но только по этой причине. Если есть желание сделать правильно, то, конечно, state теряться не должен - пример я уже привел.

**Comment by vitkarpov** [comment]
Вроде, договорились. Закрываем тогда.
