### ISSUE TITLE
Различия ключей при серверном и клиентском рендеринге

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#18]
Вьюшки в `ns` на клиенте и на сервере могут инициализироваться в разном порядке.

Мы в качестве ключа для реакт-компонента [указываем `__uniqueId` вьюшки](https://github.com/yandex-ui/noscript-react/blob/master/src/ns.viewReactMixin.js#L323), который зависит от порядка инициализации видов.

В результате, реактовый компонент одной и той вьюшки не может восстановиться на клиенте после серверного рендеринга (реакт кидает варнинг).

Кажется, стоит использовать ключ вьюшки, потому что он не зависит от порядка инициализации, а только от параметров вьюшки.

**Comment by vitkarpov** [comment]
@Rebulus что думаешь если использовать `key` самой вьюшки? по идее, будет то же самое с точки зрения работы, но связь между одним и тем экземпляром вида и реакт-компонента будет гарантирована на клиенте и сервере.

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript-react/pull/19

**Comment by Rebulus** [comment]
Ключ не гарантирует уникальность, если честно. Может существовать несколько вьюшек с одинаковым ключём, но в разных местах дерева. Но, в принципе, я не против.

**Comment by Rebulus** [comment]
Варнинг - это не страшно, он же отрисовывается всё равно 😄

**Comment by vitkarpov** [comment]
Ну да, просто получается, что реакт на клиенте зря перерисовывает, верно?

**Comment by Rebulus** [comment]
наверное да

**Comment by vitkarpov** [comment]
> Может существовать несколько вьюшек с одинаковым ключём, но в разных местах дерева.

А это не значит, что у них может быть один и тот же экземпляр компонента? Раз одинаковые ключи, логично предположить, что и шаблоны одинаковые.

**Comment by Rebulus** [comment]
Кажется, что ключ можно заиспользовать, это не должно быть критичным. На одном уровне не должно быть 2 вьюшки с одинаковым ключём.

**Comment by vitkarpov** [comment]
Ну да. Вроде ок.

**Comment by Rebulus** [comment]
Кстати, возможно это сразу сделает улучшение: https://github.com/yandex-ui/noscript-react/issues/4

**Comment by Rebulus** [comment]
Можешь проверить, если это так, то закроем 2 ишью)

**Comment by Rebulus** [comment]
Не, 4-й не поменяется, по сути же ключ новый получится и элемент перерисуется.

**Comment by vitkarpov** [comment]
ну да, если ключи разные, то и экземпляры будут разные. надо научиться строить ключ по данным.

**Comment by vitkarpov** [comment]
v1.0.2 (https://github.com/yandex-ui/noscript-react/commit/0815ef1d693e7a0db0b64c5cfd5326eca675c022)
