### ISSUE TITLE
Научиться делать подготовку страницы с ns.ViewReact на сервере

### ISSUE THREAD

**Issue by Rebulus** [yandex-ui/noscript-react#2]

**Comment by Rebulus** [comment]
@vitkarpov 
Пытаюсь реализовать рендер в HTML компонента у `root` `ns.ViewReact`.
Есть 2 предложения по реализации:
1. Создаю метод `ns.ViewReact.prototype.renderToString` и на этом всё. Логику вызова его в YATE и необходимость вызова описывает (решает) разработчик по месту использования.
2. Создаю флаг `ns.SERVER = true`. Основываясь на этом флаге, пишу `external` для YATE и вызова в `YATE` для `ns.ViewReact` корректных методов с использованием басфоруса.

Что думаешь, какой вариант тебе больше по душе?

**Comment by vitkarpov** [comment]
Думаю, надо выбирать 2 вариант — это полное решение задачи :+1:

**Comment by Rebulus** [comment]
Отлично, берусь за него

**Comment by vitkarpov** [comment]
Done!
