### ISSUE TITLE
Метод createChildren({p1: '1', p2: '2'}) не пробрасывает props потомкам бокса

### ISSUE THREAD

**Issue by i2r** [yandex-ui/noscript-react#21]
``` js
ns.layout.define('layout1', {
    'someBox@': {
        viewReact1: true
    }
});

ns.layout.define('layout2', {
    'someBox@': {
        viewReact1: true,
        viewReact2: true
    }
});

ns.ViewReact.define('viewWithPatchLayout', {
    methods: {
        patchLayout() {
            if (true) {
                return 'layout2';
            }
            return 'layout1';
        }
    },
    component: {
        render() {
            return <div>{this.createChildren({p1: '1', p2: '2'})}</div>;
        }
    }
});
```

`viewReact1` и `viewReact2` в этой ситуации не получат переданные в createChildren параметры.

**Comment by i2r** [comment]
@vitkarpov @Rebulus

**Comment by vitkarpov** [comment]
Видимо, пропсы получит бокс — непосредственный потомок, в данном случае. А для `view1` и `view2` должен прокидывать пропсы уже сам бокс, но ведь нет декларации бокса и метод `render` переопределить явно нельзя.

**Comment by Rebulus** [comment]
Да, всё так, это пропсы бокса, которыми по сути управлять не получится. А есть желание, перескочить через бокс и передать `props` потомку?

**Comment by Rebulus** [comment]
@vitkarpov @i2r Сделать это возможно и вроде не сложно 😄 Дайте знать, насколько это кретично.

**Comment by i2r** [comment]
Это необходимо при работе с коллекциями. Например, когда нужно пробросить методы из вью-коллекции потомкам.

А то сейчас остаётся только ноускрипт-вей: брать модель, тригерить на ней событие. Что выглядит странно при наличии React.

**Comment by i2r** [comment]
Только нужно, чтобы props потомков имели приоритет над передаваемыми props и не затирались при совпадении имён.

**Comment by Rebulus** [comment]
Про коллекцию я не очень понял. Могу лишь сделать так, чтобы когда ты задаёшь `props` боксу (как в твоём примере), он передавал их своим деткам. Другого способа задать `props` деткам бокса нет, поэтому приоритет тут не нужен.

**Comment by i2r** [comment]
В общем, нужен способ пробросить `props` из коллекции, состоящей из боксов, потомкам боксов.

**Comment by vitkarpov** [comment]
> Про коллекцию я не очень понял. 

Речь о том, что продолжая эти рассуждения, пропсы можно прокидывать всем вьюшкам вниз по дереву (при этом, конечно, собственные пропсы вьюшки, при совпадении имен, имеют больший приоритет).

Таким образом, ты можешь сделать `createChildren` на одном уровне лейаута, а добраться до этих данных совсем в другом. Если тебе они не нужны — ок, ты не узнаешь, что в пропсах прилетело, а если нужны: пользуйся.

@garris верно?

**Comment by i2r** [comment]
Да, всё так.

**Comment by Rebulus** [comment]
@vitkarpov мне кажется, это не очень хорошее поведение. В будущем могут возникнуть трудности с пониманием, откуда пришли опции в конкретного потомка. Кажется, лучше в таком случае прокинуть `props` нужное количество раз по всему дереву самостоятельно.

В случае с боксом, это же поведение кажется более прозрачным, т.к. бокс - сущность NS, которой ты не можешь управлять (дополнительная обёртка для решения поставленных задач). Поэтому, когда работаешь с детками view ты предполагаешь, что бокса нет и просто передаёшь опции деткам (хотя по факту они будут транслированы через бокс).

**Comment by i2r** [comment]
Давайте оставим вопрос про пробрасывание `props` вниз по дереву (раз не все согласны, что оно ожидаемо) и в рамках этой задачи только добавим пробрасывание `props` через бокс.

**Comment by vitkarpov** [comment]
Согласен. Давайте поддержим бокс.

**Comment by Rebulus** [comment]
@vitkarpov скоро отдам пулл

**Comment by Rebulus** [comment]
эм, это скорее 1.0.3

**Comment by Rebulus** [comment]
оно ничего не поламает

**Comment by Rebulus** [comment]
а использовать можно будет уже сейчас 😄

**Comment by vitkarpov** [comment]
> эм, это скорее 1.0.3

да, точняк

**Comment by vitkarpov** [comment]
v1.0.3
