### ISSUE TITLE
Не вызывается render() у потомков вида-коллекции после вставки элемента

### ISSUE THREAD

**Issue by i2r** [yandex-ui/noscript-react#25]
Есть вид-коллекция, зависящая от модели-коллекции. Потомки вида-коллекции обновляются при вызове `setState()` в коллекции через передачу обновлённых `props` (это работает).

``` javascript
viewCollection ←→ modelCollection
    viewItem
    viewItem
    …
    ↓
viewCollection.setState({…})
    ↓
viewCollection*
    viewItem*
    viewItem*
    …
```

Ожидается, что после вставки элемента в модель-коллекцию, от которой зависит вид-коллекция, все потомки-виды коллекции будут обновляться на `setState()` коллекции.

Сейчас обновляться будет только последний вставленный потомок, для всех остальных `render()` вызван не будет.

``` javascript
modelCollection.insert(itemNew)
    ↓
viewCollection
    viewItemNew
    viewItem
    viewItem
    …
    ↓
viewCollection.setState({…})
    ↓
viewCollection*
    viewItemNew*
    viewItem
    viewItem
    …
```

**Comment by i2r** [comment]
@vitkarpov @Rebulus

**Comment by Rebulus** [comment]
Думаю, это происходит из-за https://github.com/yandex-ui/noscript-react/blob/master/src/ns.viewReactMixin.js#L352-L358.
Была необходимость не обновлять то, что уже и так отрисовано по данным. `setState` не вписывается в эту концепцию, потому что по сути ты не должен вызывать обновление отображения. Всё делает ns.Update.

**Comment by Rebulus** [comment]
@i2r будет здорово, если получится вписать `setState` в общую концепцию работы с приложением в `noscript`. Но пока он работать там не будет 😞

**Comment by Rebulus** [comment]
Точнее не будет работать в отношении детак.

**Comment by vitkarpov** [comment]
> если получится вписать setState в общую концепцию работы с приложением в noscript

Да, пока что мы сделали `invalidate` вьюшки рядом с `setState`. Подумаем над тем, как это правильно сделать концептуально.

**Comment by Rebulus** [comment]
Я за запрет `setState` для ViewReact, он выбивается из концепта)

**Comment by vitkarpov** [comment]
Ну да, пока не понятно как правильно работать в этом месте с `noscript`. Потому что с реактом некоторые парадигмы становятся сомнительными.

Возможно, имеет смысл делать независимые от моделей виджеты на чистом реакте — те же комментарии, это коллекция, которая может рисоваться мэпом. Леайут этой части приложения так же инкапсулирован в самом виджете.

`ViewReact` нужен только как обертка, одна единственная, которая доставит данные в эту часть дерева приложения, а дальше — виджет сам разберется как ему жить локально. Если же поменяются модельки, то вьюшка инвалидируется и все равно так же все прозрачно перерисуется (с сохранением стейта самих компонент).

**Comment by Rebulus** [comment]
Кстати, у меня появился вопрос. А почему должны быть перерисованы детки, когда поменяться `state` у родительского компонента? Вроде для них данные никак не изменились. Приведите, пожалуйста, пример из жизни.

**Comment by vitkarpov** [comment]
> А почему должны быть перерисованы детки, когда поменяться state у родительского компонента?

Хочется пробросить новые пропсы в деток.

**Comment by vitkarpov** [comment]
@i2r насколько я понял `setState` нужен как раз чтобы вызвать этот самый процесс — проброса новый пропсов?

**Comment by i2r** [comment]
@vitkarpov да, всё так.

**Comment by Rebulus** [comment]
Хм, интересно) Тогда тут точно `invalidate + ns.page.go()` 😄

**Comment by Rebulus** [comment]
@vitkarpov @i2r будем что-то делать с этим ишью?

**Comment by Rebulus** [comment]
вроде как @vitkarpov, ты описал про особенности работы со стейтом. Если есть, что дополнить, пожалуйста, предлагайте 😄

**Comment by vitkarpov** [comment]
Мне кажется, что его нужно закрывать — мы поняли, что происходит, описали это в разделе особенностей.
