### ISSUE TITLE
Работа с setState

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#26]
У реактивной вьюшки определен shouldComponentUpdate , который смотрит на флажок  _needBeUpdated во вьюшке.

Этот флаг вычисляется при каждом апдейте и взводится при одном из следующих условий:
- view не валидно
- есть дочерние вью, которые не валидны
- view не имеет компонента

**Таким образом, если вьюшка валидна, то setState не перерисует компонент.**

Это кажется не слишком очевидным — одно дело, когда мы вызываем ноускриптовый апдейт и здесь реактивная вьюшка подчиняется обычным правилам, а другое дело, когда меняет локальный стейт реакт-компонента.

**Comment by vitkarpov** [comment]
@i2r @Rebulus Что думаете?

**Comment by i2r** [comment]
Для меня логичным кажется перерисовывать все дочерние вью на `setState`. Пусть реакт сам сделает всё от него зависящее.

**Comment by vitkarpov** [comment]
Если рассматривать реакт-вьюху как контейнер, условно вьюшка, которая лезет за данным и вызывает в своем `render` кучу других самостоятельных реакт-компонент, то может текущее поведение и имеет смысл.

Действительно, все пропсы у этих компонент могут взяться из моделей, соответственно, если они не менялись, то и нет смысла перерисовывать — все равно ничего измениться не могло.

А внутренние отдельные компонентики уже могут делать что угодно, без связи с `ns`.

**Comment by i2r** [comment]
Возможно, чтобы в дальнейшем не было соблазна написать полноценный компонент внутри ns.ViewReact и не наткнуться на все эти особенности поведения, следует изменить API такой вью: поле `component` заменить на метод `render`, который должен возвращать `JSX`.

**Comment by Rebulus** [comment]
В принципе, концепт с `render` возможен, но захочется ли всё сейчас переписать? Я бы предложил (как верно заметил @i2r) смотреть на `component` секцию как на процесс описания компонента, который не может влиять на свои дочерние компоненты, которые были созданы с помощью ns. Стейт, вроде как, сохраняется, просто дочерние `ns.ViewReact` перерисовываться не должны при его изменении.

**Comment by vitkarpov** [comment]
> Я бы предложил (как верно заметил @i2r) смотреть на component секцию как на процесс описания компонента, который не может влиять на свои дочерние компоненты, которые были созданы с помощью ns

Да, это кажется правильным подходом. И, в таком случае, АПИ может значительно упроститься.
