### ISSUE TITLE
Невозможно определить displayName у компонента

### ISSUE THREAD

**Issue by iEgit** [yandex-ui/noscript-react#27]
Из-за того, что [вот тут](https://github.com/yandex-ui/noscript-react/blob/3bbe8c17199df417a1ca9ff4fefeeb4e4877654f/src/ns.viewReactMixin.js#L196) он переопределяется.

**Comment by vitkarpov** [comment]
`displayName` всегда совпадает с названием вьюшки, потому что, по смыслу, вьюшка — самостоятельная сущность, блок по БЭМ.

**Comment by vitkarpov** [comment]
А какой кейс?

**Comment by iEgit** [comment]
``` jsx
ns.ViewReact.define('fancyView', {
    component: {
        mixins: [bemifyClassName],
        displayName: 'fancy-view'
...
```

displayName будет всегда fancyView, я хочу fancy-view для бэмных стилей

**Comment by vitkarpov** [comment]
Ага, понял.

Может тогда сделаем следующим образом:
- если displayName задан, то берем его
- иначе берем айдишник вьюшки

Более того, кажется, что вторую ветку можно сделать чуть умнее: айдишник вьюшки приводится из кемелкейса к дефисам. В таком случае, не придется каждый раз писать `displayName`, ведь как раз весь смысл был в том, чтобы этого не делать.

Что думаешь?

**Comment by iEgit** [comment]
Да, нормально

**Comment by Rebulus** [comment]
хорошо было бы указать эту особенность в README.md

**Comment by vitkarpov** [comment]
Да, конечно. Сделаю пул на это.
