### ISSUE TITLE
Реактивные вьюшки 2.0

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#32]
Постепенно приходим к следующему пониманию реактивной вьюшки. 

Реактивная вьюшка — **является поставщиком данных**, а так же обеспечивает связь с ноускриптовым лейаутом.

Что хочется переосмыслить в соответствии с этим:
- текущий интерфейс
- необходимость в коллекциях
## Интерфейс

Если смотреть на вьюшку как на поставщика данных, то теряется смысл в полной поддержке АПИ реакт-компонента, который связан непосредственно с вьюшкой.

Задача этого компонента, по сути, описать кусочек дерева реакт-компонентов (мини-лейаут получается) и прокинуть в пропсы данные из моделей и, возможно, какие-то колбеки, определенные во вью.

Соответственно, его АПИ может быть намного проще:

``` js
ns.ViewReact.define('my-react-view', {
  models: [...],
  events: {...},
  methods: {...},
  render() {
    return <div>...</div>;
  }
})
```

Нет необходимости в полной декларации реакт-компонента со всеми колбеками, по идее, при таком подходе все взаимодействие с пользователем проходит во вложенных реакт-компонентах. Если хочется следить за жизненным циклом самой вьюшки, то подойдут встроенные события видов (https://github.com/yandex-ui/noscript-react/issues/1)
## Необходимость в коллекциях

Если смотреть на вьюшку как на поставщика данных, то любая вью-коллекция может быть обычной вьюхой — ее дело запросить модель коллекцию, а далее, просто предоставить к ней доступ реакту

Пример:

``` js
ns.ViewReact.define('listing', {
  models: ['resources'],
  component: {
    render() {
      return <Listing>
         this.getModelData('resources', '.items').map((resource) => {
            // здесь любая логика формирования листинга,
            // выбор нужных компонент для показа и т.д.
            <Resource title={resource.name} .... />
                // может потребоваться пробросить другую вьюшку из лейаута,
                // со своей собственной зависимостью от моделей и т.д.
                // внутрь компонента — не вопрос.
                {this.createChildren('foo')}
            </Resource>
         })
      </Listing>;
    }
  }
})
```

Почему вообще потребовались коллекции в ns? Дорого дергать все вьюшки в реальном доме, постоянно перерисовывая, поэтому специальная сущность должна следить за тем, чтобы перерисовывать только невалидные вьюшки в коллекции.

В реакте же все проходы по всему списку видов в рендере проходят каждый раз в виртуальном доме, соответственно, такой проблемы в принципе нет.

**Comment by vitkarpov** [comment]
@Rebulus @i2r @mishk0

**Comment by i2r** [comment]
Изменения интерфейса поддерживаю.
А вот view-коллекции, кажется, можно оставить, так как, если ноускрипт перестанет вмешиваться в апдейт, то они могут быть синтаксическим сахаром для декларативной генерации потомков.

**Comment by vitkarpov** [comment]
Не понял насчет синтаксического сахара.

**Comment by i2r** [comment]
Скорее, под вопросом оказывается необходимость боксов.

**Comment by vitkarpov** [comment]
Боксы нужны, как минимум, чтобы разные экземпляры вьюшки создавались. Для того, чтобы динамически рулить лейаутом — может и не нужны, однако у нас реактивная вьюшка вроде и не должна этим заниматься.

**Comment by i2r** [comment]
> Не понял насчет синтаксического сахара.

Твой пример с коллекцией можно записать так:

``` javascript
ns.ViewReact.define('item', {
  models: ['resource'],
  render() {
    return <Resource title={this.getModelData('resource', '.name')} />;
  }
});

ns.ViewReactCollection.define('listing', {
  models: ['resources'],
  split: {
    intoViews: 'item',
    byModel: 'resources'
  },
  render() {
    return <Listing>
      {this.createChildren('item', { children: this.createChildren('foo') })}
    </Listing>;
  }
})
```

**Comment by i2r** [comment]
Правда, при нынешнем положении вещей у моего варианта есть недостаток — каждый `Resource` будет обёрнут в ещё один `<div/>`.

**Comment by vitkarpov** [comment]
Да, именно так мы сейчас делаем и не понятно зачем, когда можно проще. Кроме того управлять порядком вывода, фильтровать и т.д. становится сложнее.

**Comment by vitkarpov** [comment]
Мне просто нравится то, что становится на одну сущность меньше — коллекцию, с другой стороны, может это будет и неудобно.

**Comment by i2r** [comment]
Не понимаю, почему сложнее, кажется, одно и то же. Но декомпозиция кода лучше — каждая вью работает со своей моделью.

**Comment by Rebulus** [comment]
ns коллекция даёт возможность передать в элемент коллекции не только модель самого элемента. Если же элементу нужна только его собственная модель, то уже сейчас можно не использовать синтаксис коллекции.

**Comment by Rebulus** [comment]
почему создавалась секция `component`. Допустим вы захотите чуть более сложную логику отрисовки компонента, связанного с `ns.ViewReact`. Для этого вам потребуется чуть больше, чем метод `render`, т.е. вам захочется декомпозировать свой код в отдельные методы. И тут начнутся проблемы. В предлагаемой реализации придётся создать ещё один компонент, чтобы это реализовать.

**Comment by i2r** [comment]
Почему не создавать эти методы прямо в декларации View, а в render-е их вызвать?

**Comment by vitkarpov** [comment]
> ns коллекция даёт возможность передать в элемент коллекции не только модель самого элемента

Да, точняк. Это хорошее замечания. Допустим каждому элементу коллекции соответствует еще по экземпляру какой-то модельки, которая должна создаваться исходя из параметров для этой вьюшки. В самой коллекции это вряд ли получится описать, а через декларацию во вьюшке элемента ок.

**Comment by vitkarpov** [comment]
> вам захочется декомпозировать свой код в отдельные методы

Я могу представить ситуации в стиле:

``` js
render() {
  <div>
    {this.getSomeComplexLayout()}
    {this.getAnotherComplexLayout()}
  <div>
}
```

**Comment by i2r** [comment]
Только вот сейчас это будет выглядеть так:

``` javascript
render() {
  <div>
    {this.props.view.getSomeComplexLayout()}
    {this.props.view.getAnotherComplexLayout()}
  <div>
}
```

**Comment by Rebulus** [comment]
> Почему не создавать эти методы прямо в декларации View, а в render-е их вызвать?

Тогда, кажется, стоит совместить `methods` и `component`, что позволит избавиться от `props` 😄

**Comment by vitkarpov** [comment]
Единственное, что такое `this`. Если объявить `render` внутри `methods`, то это ок — однако это может сломать логику других вьюшек, все-таки название метода такое, вдруг встречался уже такой метод. А иначе, придется писать `this.props.view`.

**Comment by vitkarpov** [comment]
> Тогда, кажется, стоит совместить methods и component, что позволит избавиться от props

У нас `render` будет вызываться в контексте будущего экземпляра реакт-компонента, так что не понятно как их объединять.

**Comment by Rebulus** [comment]
Да, это сложный вопрос. Но контекст у `render`  подменить можно 😄 Правда и работу с `props` придётся поменять.
Например, вот так:

``` js
React.creatClass({
    render() {
        return this.props.view.render.call(this.props.view, props);
    }
})
```

**Comment by Rebulus** [comment]
А во вьюшке, уже так:

``` js
ns.ViewReact.define('some-view', {
    methods: {
        render (props)  {
            return <div>{props.someData}</div>
        }
    }
})
```

**Comment by Rebulus** [comment]
А чтобы не потерять компонент, то можно и его передать в `render`. Главное сразу определить, что это не чистый `render` React компонента.

**Comment by i2r** [comment]
> А чтобы не потерять компонент…

Ты имеешь ввиду декларацию `component`? Кажется, она не нужна.

**Comment by i2r** [comment]
> А во вьюшке, уже так…

Выглядит хорошо.

**Comment by Rebulus** [comment]
> Ты имеешь ввиду декларацию component? Кажется, она не нужна.

Я об этом:

``` js
ns.ViewReact.define('some-view', {
    methods: {
        render (component, props)  {
            return <div>{props.someData}</div>
        }
    }
})
```

Для вызова того же `setState`

**Comment by i2r** [comment]
А круто же — `ReactView` становится `statelessComponent` (он же `dumbComponent`).

**Comment by vitkarpov** [comment]
Да, нормальная тема

**Comment by i2r** [comment]
Вот как раз от использование `state` во `ViewReact` хочется избавиться.

**Comment by vitkarpov** [comment]
Не понятно даже зачем там ссылки на компонент и пропсы — зачем это может понадобится, если метод `render` не должен никаких сайд-эффектов делать. Но на всякий случай можно передать, конечно.

**Comment by vitkarpov** [comment]
По идее, он только в модельки сходит за данными, сформирует виртуальный дом и вернет его

**Comment by Rebulus** [comment]
Да, возможно. Правда вообще без `props` не обойдёшься, т.к. на них построен текущий `destroy` и ещё их почему-то нужно было передавать в `createChildren` 😄

**Comment by i2r** [comment]
> ещё их почему-то нужно было передавать

После этих изменений придётся передавать явно — это ок.

**Comment by vitkarpov** [comment]
> Правда вообще без props не обойдёшься, т.к. на них построен текущий destroy

Да, нужно разобраться с этим моментом.

**Comment by bt4R9** [comment]
Оживлю тред :)
Какие сейчас мысли по интерфейсу?
Хотелка от меня: хочется избавиться от `methods` и `component` и выполнять их где-то в одном контексте, если это возможно.

Боль такая. В модель приходит событие, надо отреагировать. Нужный метод находится внутри `component`, а событие всплывает в контексте `methods` (вида), из которого нет доступа до `component`.

**Comment by vitkarpov** [comment]
> Какие сейчас мысли по интерфейсу? Хотелка от меня: хочется избавиться от methods и component и выполнять их где-то в одном контексте, если это возможно.

Собственно, на этом и сошлись в прошлый раз —  https://github.com/yandex-ui/noscript-react/issues/32#issuecomment-223306658

`render` уедет прямо в секцию `methods`, на ряду с остальными методами и будет принимать props в аргументы, на всякий случай.

Концептуально метод `render` позволяет тебе: 
- сходить в модельку за данными и методами (`getModelData`/`getModel`)
- вернуть какой-то React-компонент, который примет тучу пропсов (на основании данных модели)
- дернуть `this.createChildren`, чтобы пробросить в `props.children` компонента другие вьюшки из лейаута

Если `render` сложный (вдруг не хочется выносить в отдельным компонент, а писать прямо во вьюшке) — можно побить все на методы прямо во вьюшке, но это чисто концептуально кажется не ок (с точки зрения тестирования такого компонента).

**Comment by vitkarpov** [comment]
В итоге, пришли к тому, что нужно отказываться от вьюшек совсем :)

https://github.com/yandex-ui/noscript-react/projects/1
