### ISSUE TITLE
Не переопределять shouldComponentUpdate

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#33]
Сейчас использование `setState` в компоненте реактивной вьюшке не очевидно — приходится дергать `this.props.view.invalidate` каждый раз когда собираешься сделать `setState`.

Есть два варианта:
- снести `shouldComponentUpdate` вовсе и оставить это на совести разработчика — если начинаются проблемы с производительностью, то нужно самостоятельно определить `shouldComponentUpdate` и условие в стиле `this.props.view.isValid()` всегда можно написать.
- сделать флажок `_needBeUpdated` публичным или определить дополнительный флажок, который будет влиять на него, чтобы разработчик мог явно пометить свою вьюшку в декларации, как «дергай апдейт компонента всегда» или «дергай апдейт компонента только если вьюшка невалидная»

Честно говоря, мне ближе первый вариант, но он радикальный — сломает обратную совместимость.

**Comment by Rebulus** [comment]
К сожалению, оставить на совести разработчика не получится, ибо любой ns.Update будет заставлять перерисовыватся React дерево, т.к. движение начинается с первого React узла и до последнего потомка.

**Comment by Rebulus** [comment]
я больше за 2-й вариант, т.е. дать возможность управлять этим процессом в ручную. Важно помнить, что это ns вьюшка, иначе вся суть ns теряется :(

**Comment by vitkarpov** [comment]
> любой ns.Update будет заставлять перерисовыватся React дерево

не очень ясно насколько это дорогая операция, учитывая что мы говорим о дифе в памяти, а не про изменения в доме

**Comment by vitkarpov** [comment]
Если принять концепцию вьюшек как поставщиков данных — то эта проблема отпадает сама собой. Потому что у контейнеров нет никакого стейта.
