### ISSUE TITLE
Универсальный _updateNode для всех типов реактовых вьюшек

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#36]
Сейчас `ns` [смотрит на `this.node` вьюшки](https://github.com/yandex-ui/noscript/blob/6a7a63b807464eadd1a8f731bb5e7eca200ef91f/src/ns.view.js#L1190), чтобы определить была ли она видна в DOM, для постановки в очередь событий `ns-view-hide`.

Нода проставляется в `_updateNode`, который сейчас вызывается только для корневых вьюшек реактивных вьюшек, которые содержат обертку сгенерированную ятем.

Сейчас, чтобы поддержать события у деток написал как-то так:

``` js
componentDidMount: function() {
    if (this.props.view.reactComponentType === 'child') {
        this.props.view.node = ReactDOM.findDOMNode(this);
    }
},
```

Возможно, имеет смысл:
- сделать общий `_updateNode` для всех типов реактивных вьюшек — дергать его на `componentDidMount`, а не в `_updateHTML` (соответственно, будет вызван не только для корневых)
- убрать ns-обертку для корневых вьюшек — получается, что компонент сам проставит ссылку но ноду и яте здесь делать нечего: не нужны `ns-view-` классы и ключи, по которым `_extactNode` сейчас находит ноду

**Comment by Rebulus** [comment]
В случае с `ns.ViewReact` надо смотреть на `this._visible`, по идее ничто другое не должно определять видимость элемента. Если это требует переопределение поведения метода  ns.View, который был унаследован, то, мне кажется, его стоит изменить.

**Comment by vitkarpov** [comment]
> Если это требует переопределение поведения метода ns.View, который был унаследован, то, мне кажется, его стоит изменить.

Да, там как раз есть завязка на наличие `this.node` — придется переопределить этот метод.

**Comment by vitkarpov** [comment]
#34 сделали другую реализацию. `this.node` у реактовой вьюшки нет. для определения того, была ли вьюшка в DOM служит `hasReactComponent` в сочетании с `this._firstUpdate`.
