### ISSUE TITLE
Заметное время между отрисовкой и сменой урла при апдейте

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#39]
Хорошо заметна разница между как таковой сменой url'а в строке адреса и фактической реакцией (перерисовкой) вида после смены url'а.

Заметили в двух местах: комменты и сайдбар от новой навигации.

Кейс 1:
- кликаем на пункт меню
- инвалидируем вьюшку, чтобы в шаблоне отрисовался после апдейта новый подкрашенный пунт
- дергаем ns.page.go
- происходит переход в другой раздел
- апдейт приходит во вьюшку, idContext поменялся, соответственно, покрасить новый пункт меню

Видно как сперва поменялся урл, а уже потом подкрасился пункт меню (где-то секунда-две проходит)

Кейс 2:
- кликаем на «Ответить» в комментариях;
- отправляем вызов в корневую вьюшку, которая меняет свой стейт, что вызывает апдейт вложенных вью;
- вложенные вью инвалидируют себя, чтобы перерисоваться в случае изменения  props ;
- апдейт приходит к вложенным вью и запускает  render , так как  props изменились, вью теперь может показать поле ввода коментария.

Проблема в том, что между кликом по «Ответить» и открытием поля комментария проходит заметное время — аналогично, секунда-две

**Comment by Rebulus** [comment]
а не может быть это связано с тем, что вы на самом деле делаете не `ns.page.go`, а его отложенный вызов?

**Comment by vitkarpov** [comment]
Можно проверить. Но вообще заметно, что время проходит именно между сменой урла и отрисовкой — урл сменился уже вследствии ns.page.go

**Comment by Rebulus** [comment]
очень похоже, что где-то есть таймаут 😄 (ваш кэп)

**Comment by vitkarpov** [comment]
Дело было в том, что создавалось адское количество экземпляров новых вьюх в боксах (менялись параметры вьюх) — соответственно, такой апдейт был реально медленным.

Когда вкрутили реально точечные перерисовки (во-первых, не создавая новых экземпляров, а инвалидируя существующие) только на паре невалидных вьюшек — стало норм.

**Comment by Rebulus** [comment]
Получается, что `ns.BoxReact` медленный на большом количестве вьюх?

**Comment by vitkarpov** [comment]
Не совсем. В боксе появлялась, фактически всего один экземпляр вьюшки, но сама вьюшка представляет из себя коллекцию, которая рекурсивно разбивается на такие же коллекции (top level комменты + ответы на них) — так что создавать заново целиком такую вьюшку и рендерить довольно дорого.

**Comment by Rebulus** [comment]
понятно, спасибо 😄
