### ISSUE TITLE
[ns.BoxReact] Улучшение перерисовки бокса

### ISSUE THREAD

**Issue by Rebulus** [yandex-ui/noscript-react#4]
Бокс - это элемент, где приложения может быть точечно перерисовано при обновлении данных.
Есть следующий пример, когда бокс мог бы заняться умной перерисовкой.

Допустим, что у нас есть бокс, в котором выводятся картинки с информацией о них. Картинки выбираются кликом по коллекции табнейлов. Лайаут такого приложения будет примерно таким:

``` js
ns.layout.define('app', {
    'app': {
        'imagesBox@': {
            'imageDesc': true
        },
        'imagesThumbnails': true
    }
});
```

Допустим, что по каким-то причинам выбираемые картинки могут совпадать и описание к ним тоже. Но, т.к. view, отрисовывающие их в боксе отличаются и ключ React компонента тоже, то они будут при выборе перерисовываться, хотя данные отличаться не будут.

Хотелось бы, чтобы бокс не вызывал перерисовки в этом случае.

**Видимые сейчас трудности:**
- Отображение вью - это реакт компонент, который связан с ней через `props`. Необходимо уметь прокидывать новые `props`, но при этом перерисовки в DOM быть не должно.

Кажется, данный момент можно решить, если связать ключ React компонента с данными.

**Comment by vitkarpov** [comment]
В **1.1.0**
