### ISSUE TITLE
replaceNode в  ReactView#_updateNode

### ISSUE THREAD

**Issue by km256** [yandex-ui/noscript-react#40]
В случае вызова `ns.Update#_updateDOM` ReactView может оказаться невалидной и будет добавлена в updateTree. Есть предположение, что для этого случая здесь 
https://github.com/yandex-ui/noscript-react/blob/v1.0.5/src/ns.viewReactMixin.js#L458
нужно сделать `ns.replaceNode(this.node, viewNode)`

**Comment by vitkarpov** [comment]
Наткнулись на то, что невалидная вьюшка, в последующих апдейтах, не перевставляет свою ноду в DOM. Т.е. `_renderElement` отдает правильную ноду, но в DOM ее не оказывается.

**Comment by Rebulus** [comment]
@km256 @vitkarpov это случай, когда родительское `ns.View` было не валидным и изменило свой контент в результате апдейта?

**Comment by Rebulus** [comment]
На этот случай есть тест: https://github.com/yandex-ui/noscript-react/blob/master/test/integration/ns.viewReact.js#L235-L299

**Comment by Rebulus** [comment]
Возможно случай другой, опишите, пожалуйста, его через `layout` 😊

**Comment by vitkarpov** [comment]
``` js
'layerApp@': function(p) {
  if (p.foo) {
    return {'contentDualPane': 'header'};
  }
  return {'contentSinglePange': 'header'};
}
```
- отрисовали `contentSinglePange` с шапкой внутри
- переключились на `contentDualPange`, отрисовалась шапка внутри
- переключились на `contentSinglePage`, ей проставился `ns-view-visible`, а для шапки внутри — нет (`ns-view-hidden` и новый компонент не привязался)

Т.е. это случай когда все вьюшки валидные и мы просто переключаем видимость.

**UPD**

Все вьюшки — обычные `ns.View`, кроме шапки.

**Comment by Rebulus** [comment]
получается, что с нодами всё хорошо?

**Comment by vitkarpov** [comment]
Когда вьюшка скрывается, то компонент анмаунтится. Поэтому когда в следующий раз мы ее не показали, то внутри ноды вьюшки компонента нет. Но это и не важно, тут видимо, проблема как раз в том, что `_showNode` не вызвался почему-то

**Comment by vitkarpov** [comment]
Надо тест писать :)

**Comment by Rebulus** [comment]
написал тесты согласно приведённому алгоритму выше, у меня в `noscript@0.7.2` всё ок
https://github.com/yandex-ui/noscript-react/pull/43
посмотрите, пожалуйста, может быть я что-то делаю не так 😄 
кстати, `noscript-react`, к сожалению, полностью не стабилен для `noscript@0.7.2`

**Comment by vitkarpov** [comment]
Да, вроде, все норм. Надо в приложении еще раз логировать — пока не понятно что за баг словили.

**Comment by Rebulus** [comment]
@vitkarpov ещё разок скажу, что текущие тесты на события не проходят полностью для `ns@0.7.2`. Есть проблемы с `ns-view-hide` событием. Может быть вы можете мигрануть на последнюю версию? Или надо будет выпустить какой-то патч для `ns@0.7.2`

**Comment by vitkarpov** [comment]
Не, конечно мигрем. Подозрительно, что ns-view-hide, может быть как раз
связано.

четверг, 30 июня 2016 г. пользователь Aleksei Simanchik написал:

> @vitkarpov https://github.com/vitkarpov ещё разок скажу, что текущие
> тесты на события не проходят полностью для ns@0.7.2. Есть проблемы с
> ns-view-hide событием. Может быть вы можете мигрануть на последнюю
> версию? Или надо будет выпустить какой-то патч для ns@0.7.2
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/yandex-ui/noscript-react/issues/40#issuecomment-229594816,
> or mute the thread
> https://github.com/notifications/unsubscribe/AC3Nv3NjJsplN-fs7ln8dQLOJUmyGh-Aks5qQ32hgaJpZM4JAFl_
> .

## 

Виктор.

**Comment by Rebulus** [comment]
@vitkarpov было бы здорово понимать, что же происходит 😄

**Comment by vitkarpov** [comment]
Ага, конечно. После того как переедем на ns@0.8.x будем еще раз смотреть — думаю, что будет понятнее.

**Comment by vitkarpov** [comment]
Не воспроизводится в приложении с ns@0.8.6

**Comment by vitkarpov** [comment]
Воспроизводится.

**Comment by Rebulus** [comment]
@vitkarpov что-нибудь слышно про эту багу?

**Comment by vitkarpov** [comment]
Done
