### ISSUE TITLE
componentDidMount вложенных компонентов вызывается когда ноды еще не в DOM

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#41]
`componentDidMount` обычных реакт-компонент, которые вложены во вьюшку, вызывается в тот момент, когда ноды еще нет реально в DOM.

Это очень печально — нельзя смотреть на размеры, положение ноды и т.д.

**Comment by vitkarpov** [comment]
Написал несколько тестов. Выяснил, что это верно только для вложенных реактивных вьюшек, а так же вьюшек в боксах.

**Comment by vitkarpov** [comment]
**UPD**

https://github.com/yandex-ui/noscript-react/pull/42

Написал тесты на 4 кейса:
- корневая реактивная вьюшка
- вложенная реактивная вьюшка
- вьюшка в ns-боксе
- вьюшка в реакт-боксе

Все тесты проходят.

**Comment by vitkarpov** [comment]
@km256 надо еще раз посмотреть в приложении.

**Comment by Rebulus** [comment]
@vitkarpov а тут что-то слышно?

**Comment by vitkarpov** [comment]
Сперва попробуем переехать на ns@0.8.x — и будем смотреть еще раз в приложении.

**Comment by vitkarpov** [comment]
Проверил в приложении на noscript@0.8.6 — проблема не воспроизводится

**Comment by vitkarpov** [comment]
Воспроизвел с 0.8.6 при повторном апдейте. Постараюсь воспроизвести в тестах.

**Comment by Rebulus** [comment]
вот жеж 😞

**Comment by Rebulus** [comment]
@vitkarpov есть какие-то новости?

**Comment by Rebulus** [comment]
@vitkarpov пыщ-пыщ!

**Comment by vitkarpov** [comment]
Не-а, пока нет :) Еще не добрались до задачки.

**Comment by Rebulus** [comment]
спасибо 😄

**Comment by mishk0** [comment]
Правильно понимаю что это происходит из-за того, что сначала рендерятся [вложенные вьюхи](https://github.com/yandex-ui/noscript/blob/33ddc12d97e9b8ecbe2208ce07e04ef6f8447727/src/ns.box.js#L256), а потом все это [вставляется в дом](https://github.com/yandex-ui/noscript/blob/33ddc12d97e9b8ecbe2208ce07e04ef6f8447727/src/ns.box.js#L266)?

**Comment by Rebulus** [comment]
Да, похоже, что так. Правда стоит смотреть не только на `ns.Box` в плане вставки, но и в [`ns.View`](https://github.com/yandex-ui/noscript/blob/master/src/ns.view.js#L1241) . Но по своей сути штука близкая, что при первой отрисовке `componentDidMount` будет вызван, когда элементы ещё не будут в DOM.

**Comment by Rebulus** [comment]
@mishk0 хотя, есть тесты, которое говорят об обратном 😞 
https://github.com/yandex-ui/noscript-react/commit/b1e3b23c3b2eb5740e18358ced95c018261a7ca6
может быть ты их можешь дополнить случаем, который на твой взгляд вызывает ошибку?

**Comment by mishk0** [comment]
@Rebulus а `ns.View.prototype._updateHTML` переопределяется же. И такой кейс у меня возникает только с боксами.

**Comment by Rebulus** [comment]
@mishk0 возможно ты можешь дописать тест на этот кейс?

**Comment by mishk0** [comment]
Да, надо будет попробовать воспроизвести на тестах.

**Comment by vitkarpov** [comment]
Понял, какой кейс не написал в тестах — когда создаются разные экземпляры вьюшки в боксе

**Comment by vitkarpov** [comment]
Кажется, вот в этом проблема

**Comment by Rebulus** [comment]
а тест сможешь добавить?

**Comment by vitkarpov** [comment]
Да, давай добавлю. @mishk0 если вдруг хотел такой же добавить точно, то не надо, ок? :)

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript-react/pull/58

**Comment by vitkarpov** [comment]
Для кейса реакт-вью непосредственно внутри яте-бокса — https://github.com/yandex-ui/noscript-react/issues/62

**Comment by vitkarpov** [comment]
В итоге:

- проверили все кейс и нашли, что падаем в одном случае: реакт-вью непосредственно внутри яте-бокса (https://github.com/yandex-ui/noscript-react/pull/42)
- запретили использования реакт-вью непосредственно внутри яте-бокса, всегда можно [обойти это на уровне лейаута](https://github.com/yandex-ui/noscript-react/issues/62#issue-198002043) (https://github.com/yandex-ui/noscript-react/pull/41)
