### ISSUE TITLE
Component не наследуется от base

### ISSUE THREAD

**Issue by i2r** [yandex-ui/noscript-react#44]
В Ноускрипте можно унаследовать один вид от другого:

``` javascript
const baseView = ns.ViewReact.define('base', {…});

ns.ViewReact.define('extendedBase', {…}, baseView);
```

Но сейчас вид `extendedBase` не унаследует `component` вида `base`.

**Comment by i2r** [comment]
@vitkarpov @Rebulus

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript-react/pull/45

**Comment by Rebulus** [comment]
Поддержали наследование компонента от `base`.

Использовать можно в следующем виде:

``` js
ns.ViewReact.define('parent', {
    component: {
        someParentMethod: function() {}
    }
});

ns.ViewReact.define('child', {
    component: {
        someChildMethod: function() {
            this.someParentMethod();
        }
    }
}, 'parent');
```

В качестве `base` можно указать только `id` `ns.ViewReact`, от которой хочется унаследоваться. Наследование происходит только компонента, само `ns.ViewReact` не наследуется.
Наследование только одноуровневое, т.е. унаследовавшись от `child`, методы `parent` доступны не будут. А также не даёт доступа к оригинальным родительским методам.

**Comment by Rebulus** [comment]
@vitkarpov написал описание получившегося решения. Кажется, что стоит его доработать:
-  Было бы здорово добавить наследование методов родительского  `ns.ViewReact`.
-  Стоит дать возможность в компоненте работать с родительскими методам, вызывая их через какой-то алиас.
-  Доработать наследование больше бесконечное число уровней.

**Comment by Rebulus** [comment]
@vitkarpov @i2r что думаете об этом?

**Comment by vitkarpov** [comment]
Согласен с тем, что можно проработать, но по необходимости.

**Comment by vitkarpov** [comment]
> Стоит дать возможность в компоненте работать с родительскими методам, вызывая их через какой-то алиас

@i2r нам нужна такая возможность прямо сейчас?

``` js
ns.ViewReact.define('bar', {
  methods: {
    bar: function() {}
  }
})
ns.ViewReact.define('foo', {
  component: {
    render: function() {
      // лезем в родительские методы
      this.props.view.bar();
    }
  }
}, 'bar')
```

Сейчас экстендится сам компонент, его методы, а не методы вьюшки.

**Comment by Rebulus** [comment]
@vitkarpov могу сказать, что это сделать достаточно просто.

**Comment by Rebulus** [comment]
https://github.com/yandex-ui/noscript-react/blob/master/src/ns.viewReact.js#L32
это место надо переписать так:

``` js
return ns.View.define.call(this, id, info, base);
```

благо в ns базовый класс берут через `this`.
https://github.com/yandex-ui/noscript/blob/master/src/ns.view.js#L1464

**Comment by Rebulus** [comment]
я сделаю сегодня дополнение по пунктам, которые описал выше.

**Comment by vitkarpov** [comment]
Круто! 👍

**Comment by vitkarpov** [comment]
Done. Подробнее напишу в релизном письме, что поддержали.
