### ISSUE TITLE
 Пропсы добавляются в виде атрибутов у ноды, которую генерит бокс

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#49]
Есть лейаут

``` js
'foo': {
  'bar@': 'baz'
}
```

Вьюшка 'foo' прокидываем пропсы своим деткам, например, `this.createChildren({ type: 'document' })`.

В результате получаем в html:

```
<div class="ns-view-foo">
  // ns-view-foo
  <div>
    // box
    <div type="document">
       // ns-view-baz
       <div>
       </div>
    </div>
  </div>
</div>
```

**UPD** Это касается не всех пропсов, а только те, которые по совместительствую являются реальными DOM-атрибутами, в таком случае в `React.createElement` они проходят фильтр и добавляются в реальный DOM — это как раз случай с `type`

**Comment by vitkarpov** [comment]
Не страшно, но кажется лишним.

**Comment by iEgit** [comment]
вообще стрёмная тема. Например, есть дочерняя view - это input и в параметрах type='password'. Получится плохо. Вообще, лишние атрибуты в html - это плохо, надо избавляться.

**Comment by vitkarpov** [comment]
Да, согласен с этим — ставим меточку «bug».

**Comment by vitkarpov** [comment]
Когда переключился на 15 реакт, то он стал сыпать варнинги про https://fb.me/react-unknown-prop

Действительно, нужно доставать из родительских пропсов только то, что нужно (в нашем случае className в дефолтном render)

**Comment by Rebulus** [comment]
У меня вопрос, а почему вы передаёте в `createChildern` аттрибуты для будущего реакт элемента и хотите, чтобы он умел их фильтровать?

**Comment by Rebulus** [comment]
Это можно сделать и сейчас в `React`.
Аля:

``` jsx
<SomeElement {...props} />
```

**Comment by Rebulus** [comment]
Хотя, кажется, я понял разницу, в нашем случае это `div` тег, а не компонент, который может и не применять к `html` разметке указанные пропсы.

**Comment by vitkarpov** [comment]
Ну да, сейчас мы в дефолтном рендере безусловно прокидываем все пропсы для дива и реакт рисует у него DOM-атрибуты
