### ISSUE TITLE
[ns.viewReactMixin] Исключение в createChildren при отсутствии вьюшки в views

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#5]
По идее, с помощью `intoLayouts` есть возможность динамически поменять лейаут для указанной вьюшки.

Пример деклараций лейаутов и коллекции:

``` js
ns.layout.define('todo-with-b', {
    todo: 'b'
});

ns.layout.define('todo-with-c', {
    todo: 'c'
});

ns.ViewReactCollection.define('todos', {
  split: {
        intoLayouts(todo) {
           if (todo.get('.foo')) {
             return 'todo-with-b';
           }
           return 'todo-with-c';
        },
        byModel: 'todos'
    }
})
```

Соответственно, во вьюшке айтема коллекции:

``` js
ns.ViewReact.define('todo', {
  ...
  render() {
    <div class="b-container">{this.createChildren('b')}</div>
    <div class="c-container">{this.createChildren('c')}</div>
  }
})
```

Хочется безусловно, как в яте, предусмотреть возможность появления в лейауте обеих вьюшек.

Сейчас будет исключение: либо `c` не найдет, либо `b`.

Кажется, правильным не кидать исключение в `createChildren` вовсе, раз есть такая возможность динамически строить лейаут.

**Comment by vitkarpov** [comment]
@Rebulus

**Comment by Rebulus** [comment]
Отлично, будет как в YATE! :smile:

**Comment by vitkarpov** [comment]
Done #6
