### ISSUE TITLE
Перейти на 15 реакт

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#50]
В приложении уже перешли, а тестируемся по-прежнему на 0.14

Попробовал переключиться и сходу заметил, что реакт стал сыпать варнингами про неизвестные пропсы (прокидываем в дефолтном рендере безусловно).

**Comment by Rebulus** [comment]
Уже частично перешли в `rc-1.1`

**Comment by Rebulus** [comment]
https://github.com/yandex-ui/noscript-react/blob/rc-1.1/package.json#L42

**Comment by Rebulus** [comment]
@vitkarpov Можно закрывать?

**Comment by vitkarpov** [comment]
Yep!
