### ISSUE TITLE
Тоже самое, но наоборот.

### ISSUE THREAD

**Issue by bt4R9** [yandex-ui/noscript-react#52]
TL;DR

Вдоволь наигравшись с `noscript-react` понял, что переписывать большие noscript view несколько сложно из-за сильной интеграции между `ns.View` и `ns.Model`.
Типичный (для меня) кейс.

```
- ns.ViewCollection
- - view-1
- - - model1
- - - state-model-1
- - view-2
- - - model2
- - - state-model-2
- - view-3
- - - model3
- - - state-model-3
```

Здесь `state-model` нужна, чтобы определять как вид `view` будет выглядеть. `view` подписан на изменение `state-model` и запускает `patchLayout`, который определяет дальнейшее дерево видов.

При переписывании этой коллекции на `noscript-react`, собственно, есть 2 пути.
1) Сделать из `ns.ViewCollection` `ns.ViewReactCollection`, а из `view` `reactView`, а в методе `render` написать `this.createChildren()`.
2) Сделать из `ns.ViewCollection` `ns.ViewReactCollection`, а дальше писать всё исключительно на реакт компонентах, то есть в render уже будет такое.

``` js
{{this.props.models.modelCollection.map((model) => {
  return <Component { ...this.getModelData(model) } />
}}
```

По некоторым личным предпочтениям, мне симпатизирует второй вариант, но вот незадача, при таком подходе нет нормальной возможности задекларировать модели и их события в дочерних видах. То есть, теперь мы работаем исключительно с React компонентами, но теряем нормальную возможность реагировать на нужные нам `noscript` события в моделях, например, чтобы обновить дочерний компонент.
Один из возможных, и вероятно правильных подходов в этой задаче — это воспринимать теперь коллекцию как отдельное реакт приложение и самому реализовать всю логику создания, подписки моделей и обновления в этой компоненте. По-большому счету, получаем огромный json данных и все подписки моделей в одном месте.
Мне такой вариант совсем не нравится, и хочется сохранить прежнее удобство декларации событий моделей, но при этом писать именно на React без оберток.

Теперь в порядке бреда, наброски костыля.

**NoscriptReactComponent**

``` js
import React from 'react';

export default class NoscriptReactComponent extends React.Component {
  constructor(props) {
    super(props);
    // здесь доступна декларация моделей через this.models и параметры для моделей
    this.bindModelsEvents();
  }

  bindModelsEvents() {
    // примерно вот это https://github.com/yandex-ui/noscript/blob/master/src/ns.view.js#L313
  }

  unbindModelsEvents() {
    // примерно вот это https://github.com/yandex-ui/noscript/blob/master/src/ns.view.js#L364
  }

  componentWillUnmount() {
    this.unbindModelsEvents();
  }
}
```

**ReactComponentInNoscriptApp**

``` js
import NoscriptReactComponent from 'components/NoscriptReactComponent';

export default class ReactComponentInNoscriptApp extends NoscriptReactComponent {
  constructor(props) {
    super(props);
  }

  get models() {
    return {
      'model': {
        'ns-model-changed': false
      },
      'model-state': {
        'ns-model-changed': false,
        'ns-model-changed.state': function() {
           // а вот тут теперь можно вызывать апдейт реакта любым удобным способом.
           // this.forceUpdate() or this.setState();
        }
      },
    }
  }

  render() {
    // do some staff
  }
}
```

Это полный бред, я не должен такого хотеть? :)

**Comment by Rebulus** [comment]
Какие плюсы от `ns.ViewReact` 😄 
1. Сохраняется возможность дикларативно описывать layout. Это позволяет определить движку, какие элементы страницы будут отрисованы и какие данные для этого надо запросить. Фактически в этом весь `noscript` 😄 
2. Noscript отслеживает невалидность данных для `ns.ViewReact` и при необходимости автоматически перерисовывает её.
3. Основываясь на 2-м пункте, нет необходимости отслеживать какие именно данные изменились. Перерисовка полностью ложится на `ns.ViewReact`. А если, необходимость есть, можно использовать `shouldComponentUpdate`, но только дочерних компонентов, т.к. по хорошему, `ns.ViewReact` - это контейнер (https://github.com/yandex-ui/noscript-react#setstate-не-вызывает-перерисовку). Очень похоже по поведению на `redux`, можно думать в том же стиле - контейнер поставляет данные, а дочерние компоненты отвечают за отрисовку.

Почему не создали просто React компонент, который был бы связан с моделями. Поэтому что `noscript` занимается анализом будущей визуализации страницы и запросом необходимых данных для её отрисовки самостоятельно. Т.е. в компонент придётся внести ещё и эти элементы, что в итоге приведёт его к `ns.ViewReact` подобию.

Поправь, пожалуйста, если на твой взгляд это не так?

**Comment by bt4R9** [comment]
Да, разумеется, всё это несомненные плюсы. :)
Мой поинт примерно такой.

```
noscript app <-> noscript-react -> react
```

В какой-то момент мне хочется уже не писать на noscript, а оперировать компонентами. Вообще, возможно, моя проблема в интерфейсе, который обсуждают тут https://github.com/yandex-ui/noscript-react/issues/32. Например, действительно неудобно, что событие модели всплывает в контексте view, а не компонента, к которому нет доступа из view. :D

**Comment by Rebulus** [comment]
Возможно я не правильно тебя понял. Да, способ описания `ns.ViewReact` стоит изменить,  но принцип работы с коллекцией от этого не поменяется 😞  - кажется всё равно придётся создать в начале `ns.ViewReact`, как элемент коллекции, а потом уже работать с вложенными компонентами.

**Comment by Rebulus** [comment]
Я понял твои рассуждения примерно так (поправь, пожалуйста, если где-то ошибся)
1. Хочу на уровне коллекции описываться её элементы используя только React компоненты.
   
   _Да это можно делать, но будет потеряна связь с моделями._
2. Хочу иметь связь с моделями, т.к. отображение зависит от их данных и изменение эти данных нужно отслеживать.
   
   _На данный момент этого нет и нужно описать кастомный компонент, который это сможет._

Встаёт вопрос, зачем потребовался `ns.ViewReact`, если вроде этих 2-х пунктов достаточно и можно было бы дописать только связь с моделями.

Но есть ещё и 3-е, которое не озвучено, но в будущем может потребоваться:
3. Хочу иметь возможность запрашивать данные для элемента коллекции.

_Если это будет компонент, который описан по правилам (1-2) выше, то `noscript` не сможет помочь в анализе и запросе данных и потребуется кастомный способ запроса данных или сообщения об этом `noscript`._

Выполняя в компоненте пункт 3, мы получим, что `ns.VieReact` 😊

**Comment by bt4R9** [comment]
Да, всё действительно упирается в пункт 3. Хотя конечно ничего не мешает написать класс для запроса этих самых моделей. Но идею я кажется уловил, таким образом и получится `ns.ViewReact`, только вывернутая наизнанку. Интеграция с ns, к сожалению, накладывает эти ограничения. :)
В общем да, убедил, надо в #32 об интерфейсе договориться и будет ок.
