### ISSUE TITLE
Сделать опциональным unmount видов

### ISSUE THREAD

**Issue by bt4R9** [yandex-ui/noscript-react#53]
Надо унести под флаг unmount компонентов при событии `hide` у вида. Это существенно ускоряет повторный рендеринг компонента.

**Comment by Rebulus** [comment]
Подскажи, пожалуйста, речь об этом месте?
https://github.com/yandex-ui/noscript-react/blob/master/src/ns.viewReactMixin.js#L324-L325

**Comment by bt4R9** [comment]
Да, именно.
По большому счету, noscript-react, в данный момент, имеет 2 недостатка:
- лишает преимуществ noscript'а при переключении элементов внутри box'а
- вместо update'а компонента при переключении вида в box'е, заново делает render и mount.

В этом issue хочется создать флаг, например `ns.Box.REACT_UNMOUNT_MODE`, который будет отвечать за unmount/hide вида. Это, во-первых, позволит сделать совместимые со всеми изменения, а во-вторых провести эксперименты.

Делаю это, а не второе (#4), потому что это просто быстрее и имеет профит. Разумеется, после #4 это будет неактуально.

**Comment by Rebulus** [comment]
#4 возможно и не реализуемо, это скорее была пометка на полях 😊

**Comment by Rebulus** [comment]
> Делаю это

Подскажи, пожалуйста, ты займёшься реализацией?

**Comment by bt4R9** [comment]
Да, ориентировочно до конца этой недели.

**Comment by vitkarpov** [comment]
> возможно и не реализуемо, это скорее была пометка на полях

Я делаю заход. На самом деле, кажется вполне реальным.

Должно получиться так, что каждой вьюшке, независимо от того сколько у нее экземпляров в боксе, соответствует один реакт-компонент — это достигается за счет того, что ключ реакт-компоненту назначается не `this.key` вьюшки, а `id` самого компонента. В коллекции это не так (иначе все ключи будут одинаковые)

**Comment by vitkarpov** [comment]
Побочный эффект — стейт-реакт компонента будет сохраняться, при переключении между боксами. У нас тесты как раз на другое поведение написаны. Пока не знаю хорошо это или нет. Обсудим отдельно.

**Comment by Rebulus** [comment]
Это да, если вьюшки однородны... Но они могут менять `layout` в зависимости от параметров и данных и задача становится сложнее... Плюс нужно как-то вьюшка статусы поменять :(

**Comment by vitkarpov** [comment]
> Но они могут менять layout в зависимости от параметров и данных и задача становится сложнее

Имеет ввиду менять лейаут внутри бокса или что сами вьюшки в зависимости от параметров и данных модели внутри, в своем шаблоне, могут выглядеть совсем по-разному?

**Comment by vitkarpov** [comment]
Если первое — то внутри бокса могут появиться разные компоненты, в зависимости от того какой вьюшке они соответствуют. Но вот если прилетают экземпляры одной и той же вьюшки, т.е. у них один id, то будет использоваться один и тот же компонент.

**Comment by Rebulus** [comment]
понял, точняк - это хорошее решение 😄

**Comment by vitkarpov** [comment]
> Плюс нужно как-то вьюшка статусы поменять

А какие именно?

**Comment by Rebulus** [comment]
про то, что они связаны с компонентом)

**Comment by vitkarpov** [comment]
ну да, нужно будет аккуратно проследить

**Comment by Rebulus** [comment]
@bt4R9 закрываю?

**Comment by bt4R9** [comment]
закрыл :)
