### ISSUE TITLE
Избавиться от глобальной зависимости от nommon

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#71]
- выделить то, что реально используется
- положить в `ns.utils`

**Comment by vitkarpov** [comment]
Что сейчас используется из `no`:

- no.extend
- ~~no.true~~ (используется один раз, проще заменить на анонимную функцию по месту)
- no.jpath
- no.inherit
- ~~no.profile~~ (такого нет, это из jsdoc-а, и там должен быть ns.profile)
- ~~no.next~~ (юзается один раз, можно заменить на `setTimeout`)

**Comment by Rebulus** [comment]
@vitkarpov покапитаню, немного. Самое сложное - `no.jpath`. Что думаешь делать с ним?

**Comment by vitkarpov** [comment]
Хороший вопрос. Пока думаю переносить как есть, в идеале, конечно подключить бы его отдельной зависимостью, чтобы было условно так:

```js
ns.utils.jpath = require('jpath')
```

А после полной поддержки commonjs и вовсе `require(jpath)` по месту использования

**Comment by vitkarpov** [comment]
Я даже видел реализации, но не уверен, что они полностью совместимые, поэтому просто так заменять неправильно

**Comment by Rebulus** [comment]
Т.е. получается, ишью не выполнимо?

**Comment by vitkarpov** [comment]
Ну, здесь идет речь о том, чтобы избавить от *глобальной* зависимости. Проблема в том, что для того, чтобы ns сейчас работал надо где-то выше подключить отдельно nommon,  и здесь две проблемы:

- собственно глобальная зависимость: нельзя просто взять ns и подключить
- подключается весь nommon, хотя, наверняка, весь не используется

Поэтому здесь цель простая: выделить то, что используется и притянуть в репо, спрятав за интерфейсом `ns.utils`.

Дальше уже можно будет накручивать и улучшать.

**Comment by vitkarpov** [comment]
После этого ишью не будет вот [такой порнографии](https://github.com/yandex-ui/noscript-react/blob/v2.x-alpha/karma.conf.js#L12-L22)

**Comment by Rebulus** [comment]
Твой пример связан с тем, как модульность устроена в nommon - там не правильно сделано 😞

**Comment by Rebulus** [comment]
Но мысль я понял, окей 😄

**Comment by vitkarpov** [comment]
Ну да, я согласен: для того, чтобы заработал jpath придется притянуть кучу всего из `nommon`, это да. Но пока это ок.

**Comment by vitkarpov** [comment]
#79
