### ISSUE TITLE
Научиться писать версию ns.VERSION

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#84]
Сейчас там 

```js
ns.VERSION = 'borschik:include:../.version';
```

а борщика больше нет

**Comment by Rebulus** [comment]
Gulp?

**Comment by vitkarpov** [comment]
Да, наверное.

**Comment by Rebulus** [comment]
Поидее и весь фреймворк должен собираться им в пакет

**Comment by vitkarpov** [comment]
Сейчас собирается вебпаком, так что, видимо, будет http://webpack.github.io/docs/list-of-plugins.html#dependency-injection

**Comment by Rebulus** [comment]
а зачем? поидее это же модуль будет из `npm`

**Comment by vitkarpov** [comment]
Не совсем. У нас до сих пор библиотеки собираются борщиком, поэтому нужно уметь подключить бандл.

**Comment by vitkarpov** [comment]
Сейчас все собирается в виде umd-модуля, чтобы можно было и так и так использовать.

**Comment by Rebulus** [comment]
`amd`?

**Comment by Rebulus** [comment]
аа, понял `Universal Module Definition`

**Comment by vitkarpov** [comment]
#88
