### ISSUE TITLE
show может быть вызван на видах до того, как их нода физически окажется в DOM'е

### ISSUE THREAD

**Issue by i2r** [yandex-ui/noscript-react#94]
https://github.com/i2r/noscript-react-todomvc/tree/subview-show-test

Нужно открыть консоль и обновить страницу, затем вызвать `ns.page.go()` — вид SUB выполнит htmlinit и show, в то время как вид VIEW продолжит ждать загрузки модели.

Т.е. если новый апдейт придёт до того, как модели родительского вида будут загружены, то методы на show детей будут вызваны.

Характерно только для noscript-react.
В тесте для noscript проблемы нет:
https://github.com/i2r/noscript-react-todomvc/tree/subview-show-test-pure-noscript

**Comment by i2r** [comment]
@vitkarpov

**Comment by vitkarpov** [comment]
https://github.com/i2r/noscript-react-todomvc/commit/411da71f50aa785f8eb737c41c820b41717e93c4#diff-0364f57fbff2fabbe941ed20c328ef1aR39

что-то не понял: почему бокс задекларирован как вьюшка? кажись это не бокс тогда :)

**Comment by vitkarpov** [comment]
А, не. Там ниже вьюшка с таким же названием. Не уверен, что это ок, кстати. Поменяю в тесте.

**Comment by vitkarpov** [comment]
Нашел в чем беда – `hasChildrenNeedBeUpdated` рекурсивно спускается по деткам заполняя попутно объект с событиями, и проходит дальше асинхронной вьюшки, а не должен.

**Comment by vitkarpov** [comment]
Сделаю пул

**Comment by vitkarpov** [comment]
#95

**Comment by vitkarpov** [comment]
1.1.4
